Repository red-hat-data-services/kserve, pull requests merged in 2025-02, with the labels that each got.

#896 Updated storage initializer dockerfile for ppc64le
  Dockerfiles/storage-initializer.Dockerfile.konflux
Labels: approved, lgtm, needs-ok-to-test

#995 2/13/2025 Sync RHOAI main branch with ODH release-v0.14 branch
  config/component_metadata.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/controller_test.go
  pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go
  pkg/controller/v1alpha1/inferencegraph/suite_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  test/crds/route.openshift.io_routes.yaml
Labels: approved, lgtm, do-not-merge/hold

#1005 [Cherry-pick][RHOAIENG-19923] - ose-oauth-proxy image for kserve and model mesh sh…
  config/overlays/odh/params.env
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
Labels: approved, lgtm

#1094 [Cherry-pick] Cleanup the filepath in createNewFile to avoid path traversal issue
  pkg/agent/storage/https.go
Labels: approved, lgtm
