Repository red-hat-data-services/kserve, pull requests merged in 2025-08, with the labels that each got.

#1731 update params.env
  config/overlays/odh/params.env
Labels: approved

#1778 Revert params.env
  config/overlays/odh/params.env
Labels: approved, lgtm

#1781 Sync/250825 release v0.15 into main
  .flake8
  charts/kserve-resources/templates/clusterrole.yaml
  cmd/manager/main.go
  config/crd/full/serving.kserve.io_llminferenceserviceconfigs.yaml
  config/crd/full/serving.kserve.io_llminferenceservices.yaml
  config/monitoring/llmisvc/engine_vllm_monitor.yaml
  config/monitoring/llmisvc/kustomization.yaml
  config/monitoring/llmisvc/rbac.yaml
  config/monitoring/llmisvc/scheduler_monitor.yaml
  config/rbac/role.yaml
  docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu-no-scheduler.yaml
  go.mod
  go.sum
  pkg/apis/serving/v1alpha1/llm_inference_service_lifecycle.go
  pkg/apis/serving/v1alpha1/llm_inference_service_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/llmisvc/config_loader.go
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/config_merge_test.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/controller_workload_storage_int_test.go
  pkg/controller/llmisvc/fixture/gwapi_builders.go
  pkg/controller/llmisvc/fixture/llmisvc_builders.go
  pkg/controller/llmisvc/lifecycle_crud.go
  pkg/controller/llmisvc/monitoring.go
  pkg/controller/llmisvc/router.go
  pkg/controller/llmisvc/router_discovery.go
  pkg/controller/llmisvc/router_validation.go
  pkg/controller/llmisvc/scheduler.go
  pkg/controller/llmisvc/workload.go
  pkg/controller/llmisvc/workload_multi_node.go
  pkg/controller/llmisvc/workload_ocp_scc.go
  pkg/controller/llmisvc/workload_single_node.go
  pkg/controller/llmisvc/workload_storage.go
  pkg/controller/llmisvc/workload_tls_self_signed_istio.go
  pkg/credentials/service_account_credentials.go
  pkg/credentials/service_account_credentials_test.go
  pkg/testing/ctrl.go
  pkg/testing/httproute_matchers.go
  pkg/testing/meta_matchers.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  test/crds/monitoring_podmonitor.yaml
  test/crds/monitoring_servicemonitor.yaml
  test/crds/serving.kserve.io_all_crds.yaml
Labels: approved, lgtm

#1783 add localmodel and localmodel-agent Konflux Dockerfiles
  Dockerfiles/localmodel-agent.Dockerfile.konflux
  Dockerfiles/localmodel.Dockerfile.konflux
Labels: approved, do-not-merge/hold

#1785 Update params.env
  config/overlays/odh/params.env
Labels: lgtm
