Repository red-hat-data-services/kserve, pull requests merged in 2025-04, with the labels that each got.

#1394 [RHOAIENG-7287] - storage initializer - update python to 3.11
  Dockerfiles/storage-initializer.Dockerfile.konflux
Labels: approved

#1437 change oauth proxy image to be compatible with multi arch
  config/overlays/odh/params.env
Labels: approved, lgtm

#1436 change oauth proxy image to be compatible with multi arch
  config/overlays/odh/params.env
Labels: approved

#1441 set unversioned python for alternatives
  Dockerfiles/storage-initializer.Dockerfile.konflux
Labels: approved, lgtm

#1453 [cherry-pick] add flag to control tls behavior for kserve router
  cmd/router/main.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
Labels: approved, lgtm

#1454 [Cherry pick] [RHOAIENG-23169] - StorageInitializer fails do download models from h…
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
Labels: approved, lgtm

#1459 [RHOAIENG-24212] - storage initializer - Fix storage intializer build for s390x
  Dockerfiles/storage-initializer.Dockerfile.konflux
Labels: lgtm, ok-to-test

#1465 Enhance InjectAgent to Handle Only HTTPGet, TCP Readiness Probes (#4012)
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
Labels: approved, lgtm
